package com.geoffchan.glucosewidget

import android.annotation.SuppressLint
import android.content.Intent
import android.os.Bundle
import android.webkit.WebView
import androidx.activity.ComponentActivity
import androidx.activity.compose.BackHandler
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.KeyboardArrowLeft
import androidx.compose.material.icons.automirrored.filled.KeyboardArrowRight
import androidx.compose.material.icons.filled.Delete
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.viewinterop.AndroidView
import java.io.File
import java.time.LocalDate
import java.time.format.DateTimeFormatter
import java.util.Locale

/** Old entry point (the "report ready" notification): forwards to the Reports tab. */
class ReportsActivity : ComponentActivity() {
    companion object { const val EXTRA_OPEN = "open" } // file name to open straight away

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        startActivity(
            Intent(this, MainActivity::class.java)
                .putExtra(EXTRA_TAB, TAB_REPORTS)
                .apply { intent.getStringExtra(EXTRA_OPEN)?.let { putExtra(EXTRA_OPEN, it) } }
                .addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP or Intent.FLAG_ACTIVITY_SINGLE_TOP),
        )
        finish()
    }
}

/**
 * The Reports tab: weekly reports pushed to files/reports/ (see
 * tools/push-report.sh) and Ray's reports from the chat ("ray-…",
 * JavaScript off), opened in a WebView. Weekly reports are self-contained
 * HTML generated by analysis/report.py on the Mac; nothing is fetched from
 * the network except the web fonts, which fall back to system faces offline.
 */
@Composable
fun ReportsScreen(open: File?, onOpen: (File?) -> Unit) {
    val context = LocalContext.current
    val dir = remember { reportsDir(context) }
    var files by remember { mutableStateOf(listReports(dir)) }
    BackHandler(enabled = open != null) { onOpen(null) }
    val idx = open?.let { f -> files.indexOfFirst { it.name == f.name } } ?: -1
    val newer = if (idx > 0) files[idx - 1] else null          // list is newest-first
    val older = if (idx >= 0 && idx < files.size - 1) files[idx + 1] else null
    Column(Modifier.fillMaxSize()) {
        Row(
            Modifier.fillMaxWidth().padding(start = if (open != null) 4.dp else 18.dp, end = 4.dp, top = 8.dp, bottom = 8.dp),
            verticalAlignment = Alignment.CenterVertically,
        ) {
            if (open != null) {
                IconButton(onClick = { onOpen(null) }) { Icon(Icons.AutoMirrored.Filled.KeyboardArrowLeft, "Back") }
            }
            Text(
                open?.let { reportTitle(it.name) } ?: "Reports",
                style = MaterialTheme.typography.titleLarge,
                maxLines = 1,
                modifier = Modifier.weight(1f),
            )
            if (open != null) {
                // Step between reports without going back to the list.
                IconButton(onClick = { onOpen(older) }, enabled = older != null) {
                    Icon(Icons.AutoMirrored.Filled.KeyboardArrowLeft, "Older")
                }
                IconButton(onClick = { onOpen(newer) }, enabled = newer != null) {
                    Icon(Icons.AutoMirrored.Filled.KeyboardArrowRight, "Newer")
                }
            }
        }
        if (open != null) {
            ReportWebView(open)
        } else if (files.isEmpty()) {
            Column(
                Modifier.fillMaxWidth().padding(32.dp),
                horizontalAlignment = Alignment.CenterHorizontally,
                verticalArrangement = Arrangement.spacedBy(10.dp),
            ) {
                RayAvatar(64.dp)
                Text(
                    "No reports yet. Ask Ray for one, or run the weekly report on the Mac.",
                    style = MaterialTheme.typography.bodyMedium,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                    textAlign = androidx.compose.ui.text.style.TextAlign.Center,
                )
            }
        } else {
            val c = LocalSugar.current
            LazyColumn(
                Modifier.padding(horizontal = 14.dp),
                verticalArrangement = Arrangement.spacedBy(8.dp),
            ) {
                items(files, key = { it.name }) { f ->
                    val byRay = RayTools.isRayReport(f.name)
                    Surface(
                        onClick = { onOpen(f) },
                        shape = RoundedCornerShape(18.dp),
                        color = MaterialTheme.colorScheme.surfaceContainer,
                        border = BorderStroke(1.dp, MaterialTheme.colorScheme.outlineVariant),
                        modifier = Modifier.fillMaxWidth(),
                    ) {
                        Row(
                            Modifier.padding(start = 12.dp, top = 10.dp, bottom = 10.dp),
                            verticalAlignment = Alignment.CenterVertically,
                        ) {
                            if (byRay) {
                                RayAvatar(36.dp)
                            } else {
                                Box(Modifier.size(36.dp).background(c.soft, RoundedCornerShape(10.dp)), contentAlignment = Alignment.Center) {
                                    Text("▤", color = c.onSoft, style = MaterialTheme.typography.titleMedium)
                                }
                            }
                            Column(Modifier.weight(1f).padding(start = 12.dp)) {
                                Text(reportTitle(f.name), style = MaterialTheme.typography.bodyLarge.copy(fontWeight = FontWeight.Bold))
                                Text(
                                    if (byRay) "Ray's report" else "Weekly report",
                                    style = MaterialTheme.typography.labelMedium,
                                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                                )
                            }
                            IconButton(onClick = { f.delete(); files = listReports(dir) }) {
                                Icon(Icons.Filled.Delete, "Delete report", tint = MaterialTheme.colorScheme.onSurfaceVariant)
                            }
                        }
                    }
                }
                item { Spacer(Modifier.height(8.dp)) }
            }
        }
    }
}

@SuppressLint("SetJavaScriptEnabled")
@androidx.compose.runtime.Composable
private fun ReportWebView(file: File) {
    AndroidView(
        factory = { ctx ->
            WebView(ctx).apply {
                // the weekly report draws its charts in JS; Ray's reports are static HTML + SVG
                settings.javaScriptEnabled = !RayTools.isRayReport(file.name)
                settings.allowFileAccess = true        // file:// under our own filesDir
                settings.domStorageEnabled = false
                setBackgroundColor(0xFF121518.toInt())
            }
        },
        update = {
            it.settings.javaScriptEnabled = !RayTools.isRayReport(file.name)
            it.loadUrl("file://${file.absolutePath}")
        },
        modifier = Modifier.fillMaxSize(),
    )
}

fun reportsDir(ctx: android.content.Context): File = File(ctx.filesDir, "reports").apply { mkdirs() }

fun listReports(dir: File): List<File> =
    dir.listFiles { f -> f.isFile && f.name.endsWith(".html") }?.sortedByDescending { it.name } ?: emptyList()

private val NAME_RE = Regex("""^report-(\d{4}-\d{2}-\d{2})_(\d{4}-\d{2}-\d{2})\.html$""")

/** "report-2026-09-01_2026-09-06.html" → "Sep 1 – Sep 6, 2026"; anything else shows its file name. */
fun reportTitle(fileName: String): String {
    RayTools.reportTitleOf(fileName)?.let { return it }
    val m = NAME_RE.find(fileName) ?: return fileName.removeSuffix(".html")
    val (a, b) = m.destructured
    val fa = LocalDate.parse(a); val fb = LocalDate.parse(b)
    val md = DateTimeFormatter.ofPattern("MMM d", Locale.CANADA)
    return "${fa.format(md)} – ${fb.format(md)}, ${fb.year}"
}
