package com.geoffchan.glucosewidget

import android.annotation.SuppressLint
import android.os.Bundle
import android.webkit.WebView
import androidx.activity.ComponentActivity
import androidx.activity.compose.BackHandler
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.KeyboardArrowLeft
import androidx.compose.material.icons.automirrored.filled.KeyboardArrowRight
import androidx.compose.material.icons.filled.Delete
import androidx.compose.material3.Card
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.darkColorScheme
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.viewinterop.AndroidView
import java.io.File
import java.time.LocalDate
import java.time.format.DateTimeFormatter
import java.util.Locale

/**
 * Lists weekly reports pushed to files/reports/ (see tools/push-report.sh)
 * and opens one in a WebView. Reports are self-contained HTML generated by
 * analysis/report.py on the Mac; nothing is fetched from the network except
 * the web fonts, which fall back to system faces offline.
 */
class ReportsActivity : ComponentActivity() {
    companion object { const val EXTRA_OPEN = "open" } // file name to open straight away

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        val dir = reportsDir(this)
        val openFirst = intent.getStringExtra(EXTRA_OPEN)?.let { File(dir, it) }?.takeIf { it.isFile }
        setContent {
            MaterialTheme(colorScheme = darkColorScheme()) {
                var files by remember { mutableStateOf(listReports(dir)) }
                var open by remember { mutableStateOf(openFirst) }
                BackHandler(enabled = open != null) { open = null }
                val idx = open?.let { f -> files.indexOfFirst { it.name == f.name } } ?: -1
                val newer = if (idx > 0) files[idx - 1] else null          // list is newest-first
                val older = if (idx >= 0 && idx < files.size - 1) files[idx + 1] else null
                // Scaffold supplies the status-bar inset and the theme's content colours,
                // same as MainActivity, so the header never sits under the camera cutout.
                Scaffold { padding ->
                    Column(Modifier.fillMaxSize().padding(padding)) {
                        Row(
                            Modifier.fillMaxWidth().padding(horizontal = 8.dp, vertical = 4.dp),
                            verticalAlignment = Alignment.CenterVertically,
                        ) {
                            IconButton(onClick = { if (open != null) open = null else finish() }) {
                                Icon(Icons.AutoMirrored.Filled.KeyboardArrowLeft, "Back")
                            }
                            Text(
                                open?.let { reportTitle(it.name) } ?: "Reports",
                                style = MaterialTheme.typography.titleLarge,
                                modifier = Modifier.weight(1f),
                            )
                            if (open != null) {
                                // Step between weeks without going back to the list.
                                IconButton(onClick = { open = older }, enabled = older != null) {
                                    Icon(Icons.AutoMirrored.Filled.KeyboardArrowLeft, "Previous week")
                                }
                                IconButton(onClick = { open = newer }, enabled = newer != null) {
                                    Icon(Icons.AutoMirrored.Filled.KeyboardArrowRight, "Next week")
                                }
                            }
                        }
                        val current = open
                        if (current != null) {
                            ReportWebView(current)
                        } else if (files.isEmpty()) {
                            Text(
                                "No reports yet. Run the weekly report on the Mac and it will appear here.",
                                style = MaterialTheme.typography.bodyMedium,
                                modifier = Modifier.padding(24.dp),
                            )
                        } else {
                            LazyColumn(Modifier.padding(horizontal = 12.dp)) {
                                items(files, key = { it.name }) { f ->
                                    Card(
                                        onClick = { open = f },
                                        modifier = Modifier.fillMaxWidth().padding(vertical = 4.dp),
                                    ) {
                                        Row(
                                            Modifier.padding(start = 16.dp, top = 4.dp, bottom = 4.dp),
                                            verticalAlignment = Alignment.CenterVertically,
                                        ) {
                                            Text(
                                                reportTitle(f.name),
                                                Modifier.weight(1f).padding(vertical = 12.dp),
                                                style = MaterialTheme.typography.bodyLarge,
                                            )
                                            IconButton(onClick = { f.delete(); files = listReports(dir) }) {
                                                Icon(Icons.Filled.Delete, "Delete report")
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

@SuppressLint("SetJavaScriptEnabled")
@androidx.compose.runtime.Composable
private fun ReportWebView(file: File) {
    AndroidView(
        factory = { ctx ->
            WebView(ctx).apply {
                settings.javaScriptEnabled = true      // the report draws its charts in JS
                settings.allowFileAccess = true        // file:// under our own filesDir
                settings.domStorageEnabled = false
                setBackgroundColor(0xFF121518.toInt())
            }
        },
        update = { it.loadUrl("file://${file.absolutePath}") },
        modifier = Modifier.fillMaxSize(),
    )
}

fun reportsDir(ctx: android.content.Context): File = File(ctx.filesDir, "reports").apply { mkdirs() }

fun listReports(dir: File): List<File> =
    dir.listFiles { f -> f.isFile && f.name.endsWith(".html") }?.sortedByDescending { it.name } ?: emptyList()

private val NAME_RE = Regex("""^report-(\d{4}-\d{2}-\d{2})_(\d{4}-\d{2}-\d{2})\.html$""")

/** "report-2026-09-01_2026-09-06.html" → "Sep 1 – Sep 6, 2026"; anything else shows its file name. */
fun reportTitle(fileName: String): String {
    val m = NAME_RE.find(fileName) ?: return fileName.removeSuffix(".html")
    val (a, b) = m.destructured
    val fa = LocalDate.parse(a); val fb = LocalDate.parse(b)
    val md = DateTimeFormatter.ofPattern("MMM d", Locale.CANADA)
    return "${fa.format(md)} – ${fb.format(md)}, ${fb.year}"
}
